[placeholders.app_code_name]
type = "string"
prompt = "Application name for use in code (must be in PascalCase)?"
regex = "^([A-Z][a-z0-9_]*)+$"

[placeholders.app_display_name]
type = "string"
prompt = "Application name for display to the user?"

[placeholders.publisher_display_name]
type = "string"
prompt = "Application publisher name for display to the user?"
default = ""